# Config options

# CACHING:
# - cache streams               yes / no                                yes
# - cache images                yes / no                                yes
# - cache images (as text)      yes / no                                yes

# APPEARANCE
# - colors?                     color list (by rgb)                     color defaults
# - loading animations          animation list (by string name)         animation defaults
# - icons?                      icon (string)                           icon defaults

# PATHS:
# CACHE_PATH = "..."            path (string)                           ~/.cache/moroder
# COOKIES_PATH = "..."          path (string)                           ~/.config/moroder

# NETWORK
# - FETCH_ALBUMS                yes / no                                yes
# - image resolution prio.      lowest / medium(?) / highest            highest
# - SEARCH_RESULT_LIMIT         int                                     40

# API KEYS
# LASTFM_API_LEY = "25de..."    string                                  none

# DISCORD
# - enable
# - status label                album / title / artist string           artist
